
package visitor.management.system;

import java.awt.HeadlessException;
import javax.swing.JFrame;
import static visitor.management.system.VisitorManagementSystem.mainPage;
import static visitor.management.system.VisitorManagementSystem.window;


public class AdminFunctions extends javax.swing.JApplet {
VisitorManagementSystem vos;
VisitorDetailsObjects model;
public JFrame adminFrame;
    public AdminFunctions(VisitorManagementSystem vos) throws HeadlessException {
        this.vos = vos;
    }
    /**
     * Initializes the applet AdminFunctions
     */

    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewVisitor = new javax.swing.JButton();
        addVisitor = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("WELCOME ADMIN");

        viewVisitor.setText("View Visitors");
        viewVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVisitorActionPerformed(evt);
            }
        });

        addVisitor.setText("Add Visitor");
        addVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(addVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(viewVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVisitorActionPerformed
        // TODO add your handling code here:
        
         vos.visitorListFrame = new JFrame("Visitors List");
        vos.visitorListFrame.setContentPane(vos.vlist);
        vos.visitorListFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        vos.visitorListFrame.pack();    
        vos.vlist.set(model);
        //Arrange the components.
        //System.out.println(theApplet.getSize());
        vos.visitorListFrame.setVisible(true); 
        vos.adminFxnFrame.setVisible(false);
        
        
        
    }//GEN-LAST:event_viewVisitorActionPerformed

    private void addVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitorActionPerformed

        vos.visitorListFrame = new JFrame("Visitor Details");
        vos.visitorListFrame.setContentPane(vos.v);
        vos.visitorListFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        vos.visitorListFrame.pack();              
        //Arrange the components.
        //System.out.println(theApplet.getSize());
        vos.visitorListFrame.setVisible(true); 
        vos.adminFxnFrame.setVisible(false);
        
            
        
 

 
    }//GEN-LAST:event_addVisitorActionPerformed
public void set(VisitorDetailsObjects vos)
    {
        this.model=vos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVisitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewVisitor;
    // End of variables declaration//GEN-END:variables
}


